### ISSUE TITLE
lifetime issues

### ISSUE THREAD

**Issue by MarkSwanson** [jpernst/rental#16]
I'm having a hard time returning optional references to internal intermediate structs.

My SomeHelper::get_key() works fine (it calls get_keys_iter() and returns a &str)

get_keys_iter() fails - because returning the iterator has lifetime problems.

```
Some(rent_context) => {
                let value = rent_context.maybe_ref_rent(|new_request_v3| {
                    match new_request_v3.get_things() {
                        Ok(things) => {
                            SomeHelper::get_keys_iter(&things)
                        },
                        Err(e) => ...
                    }
                });
                Some(value)
            },
```
iter is basically a struct_list::Reader<'a,::common_capnp::cookie::Owned<>>
inside of:
impl <'a,> Reader<'a,> {
...
}

The main problem seems to be that rustc is telling me that the result of SomeHelper::get_keys_iter(&things) can't live beyond the anonymous lifetime as defined by get_things() {}

This doesn't make sense to me because I'm returning references outside of get_things() in nearly identical functions. The only difference with the working functions is that I'm returning the contents of the iterator, not the iterator itself.

Is there some obvious thing I'm missing?

Thanks!

**Comment by jpernst** [comment]
There's too many moving parts here for me to be sure, but I suspect it's because the iterator itself has a rental lifetime in it because it borrows from the rental closure argument, whereas the output of the iterator doesn't.

**Comment by MarkSwanson** [comment]
Yeah, there are a lot of moving parts. Thanks for your thoughts.
I *think* the output of the iterator has a rental lifetime because if I return the output (instead of the iterator) it works.
I don't know for sure because rustc gives me this error:
expected test_capnproto::request_v3_capnp::request_v3::Reader<'_>, found test_capnproto::request_v3_capnp::request_v3::Reader<'_>
Note the expected/found are identical? this befuddles me :-)

I'll circle back shortly and fork rental to provide a tiny working example in the tests dir.

**Comment by MarkSwanson** [comment]
I think I found the problem: capn proto has methods like get_vars(self) -> NotARef {}

In the rental closure I can then attempt to return &not_a_ref, but this lifetime is limited to the scope of the closure.

Is there any way for me to manually fix the lifetime?
Do you think that borrow() can help? (somehow use the exposed lifetimes?)

Thanks.

**Comment by jpernst** [comment]
`borrow()` could work, but just keep in mind that it's very unsafe because the lifetimes it returns are false, which could lead to subtle memory corruption if not handled with extreme care. Sorry I couldn't offer more constructive advice, but I'm just not familiar enough with capnproto or its api to offer useful architectural advice.

**Comment by MarkSwanson** [comment]
Ok, I forked and created some test code that should help me ask the right questions:

https://github.com/MarkSwanson/rental

cargo test -> compiles but hangs because of stdin/stdout issues with the test harness.

Wrt hang - I'm hoping it will be good enough to be able to see the code and rustc error messages.

If you search for 'Question' in tests/capnproto.rs you should see exactly what I'm trying to do, and uncommenting the related Fns should show you the rustc errors I'm seeing.

Thanks in advance for any suggestions!

**Comment by MarkSwanson** [comment]
Before I forget, one solution might be to patch capn proto to generate additional Fns that accept &self and return references. F.e.

original: pub fn get_strings(self) -> Result<text_list::Reader<'a>>
new:
pub fn get_strings_ref(&'a self) -> Result<&'a text_list::Reader<'a>>

**Comment by MarkSwanson** [comment]
Progress!

I don't remember why I did this, but in a *few* Fns I had this (bad) line of code:
```
Some(ref rent_context) => rent_context.maybe_ref_rent(|new_request_v3: &new_request_v3::Reader| {
```

I have found that removing the type has fixed one of my compile problems. Example:
```
            Some(ref rent_context) => rent_context.maybe_ref_rent(|new_request_v3| {
```
I'll spend some time investigating to see how much success bubbles up...

**Comment by MarkSwanson** [comment]
Ok, my questions/requests still stand - removing the type fixed a couple of Fns but this was an unrelated issue.

**Comment by jpernst** [comment]
Unfortunately it's not possible for rental to return any custom type with a rental lifetime, since that would require HKT, so the functions that currently exist are probably the best that can be done for now.

**Comment by jpernst** [comment]
As per the code, the type you're trying to return in question 1 contains a rental lifetime in its type, specificaly `'reader`, so returning it is specifically not allowed as it is unsafe. I'm not sure what type `get_strings` is, but from the context I wager it also contains a rental lifetime because it borrows from `point`, so it's also not eligible for `ref_rent`.

**Comment by MarkSwanson** [comment]
Got it. You're right about get_strings.

Well, it looks like the most optimal path would be to rewrite my code to use Rc<RefCell<T>>. 
Now I know how far I can push things atm.

One last thing, you mention HKT, but what about Associated Type Constructors? Nikko seems to be investigating ATC instead of HKT. Would you be able to make this work with ATC?

Thanks.

**Comment by jpernst** [comment]
What might be possible to implement is returning bare references inside custom containers, eg `Option<T>`, `Result<T>`, etc, rather than needing separate functions for each. It will never be safe to return opaque types that take a rental lifetime param since it's impossible to know how it's used internally. But in any case, I'm looking forward to exploring that feature once we get a usable version in nightly.
