### ISSUE TITLE
Reference to parent struct

### ISSUE THREAD

**Issue by manuels** [jpernst/rental#26]
I am trying to implement a struct that references its parent struct. Something like this struct `A`:

```
struct A<'a> {
  b: B<'a>,
}

struct B<'a> {
  parent: &'a A<'a>,
}
```

I was not able to implement this using rental. Maybe you can give me a hint how to do this?

**Comment by jpernst** [comment]
Rental isn't really designed to support this kind of circular data structure. Perhaps a crate like [petgraph](https://crates.io/crates/petgraph) would be more suitable for your scenario.

**Comment by manuels** [comment]
Great, thanks for the fast response!
