### ISSUE TITLE
Unable to just use rental::* in a 2018 edition crate

### ISSUE THREAD

**Issue by tylerhawkes** [jpernst/rental#28]
This is just a cosmetic issue, but I can't get a simple 2018 edition crate to compile unless I add
```
#[macro_use]
extern crate rental;
```

Without that it gives the error
```
error: cannot find derive macro `__rental_structs_and_impls` in this scope
  --> src/main.rs:14:1
   |
14 | / rental! {
15 | |   pub mod model {
16 | |     #[rental]
17 | |     pub struct Model {
...  |
22 | |   }
23 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

If there's nothing that can be done about it, adding some documentation mentioning this would be great.

**Comment by jpernst** [comment]
Thanks for the heads-up. I'll add a note to the docs about this soon.

**Comment by jpernst** [comment]
New version published with a note about this in the docs.
