### ISSUE TITLE
How can I recreate the suffix?

### ISSUE THREAD

**Issue by shepmaster** [jpernst/rental#32]
```rust
#[macro_use]
extern crate rental;

rental! {
    mod rent_defiler {
        use std::slice::IterMut;

        #[rental_mut]
        pub struct RentDefiler {
            seq: Vec<u32>,
            current: IterMut<'seq, u32>,
        }
    }
}

struct Defiler(rent_defiler::RentDefiler);

impl Defiler {
    fn new(mut seq: Vec<u32>) -> Self {
        Self(rent_defiler::RentDefiler::new(seq, |seq| seq.iter_mut()))
    }

    fn reset(&mut self) {
        // What goes here?
        // Want to reset the iterator back to the original value.
    }
}
```

**Comment by jpernst** [comment]
The best way to do this would be to use `into_head()` to destroy the rental struct and get the `Vec` back out. Then you can recreate the rental struct with a new iterator. To do this you may need to wrap the rental struct in an `Option`, or use something like the `take-mut` crate.

**Comment by shepmaster** [comment]
I was afraid of that.

Is there anything conceptually invalid about destroying all of the suffixes and recreating them (I know this is a difficult question to answer without some digging!)

**Comment by jpernst** [comment]
That's effectively what `into_head` already does. A rental struct is nothing more than the original value you give it and the values you create in the closures. `into_head` just drops all the suffixes and lets you rebuild them with the original head again.
