### ISSUE TITLE
When `rental!` used via full path, implementation details leak

### ISSUE THREAD

**Issue by nagisa** [jpernst/rental#33]
```
error: cannot find derive macro `__rental_structs_and_impls` in this scope
   --> src/blah/mod.rs:82:1
    |
82  | / rental::rental! {
83  | |     mod rentals {
84  | |         use foo;
85  | |         use bar;
...   |
116 | |     }
117 | | }
    | |_^
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

I think if the derives inside the `rental!` macro were using `$crate::__rental_structs_and_impls` or whatever, things would be working?

**Comment by jpernst** [comment]
The first thing to try is to explicitly include the rental crate with the `macro_use` attribute. Rental doesn't support rust 2018's implicit crate inclusion.

**Comment by Stargateur** [comment]
would be nice to include this information in the readme
