### ISSUE TITLE
Rental structures without Box

### ISSUE THREAD

**Issue by ufoscout** [jpernst/rental#43]
Is it possible to create `rental` structs without Boxing the rented object? Maybe using `Pin` ?
something like:
```rust
rental! {
	mod rentals {
		use super::*;

		#[rental_mut]
		pub struct SimpleMut {
			foo: Pin<Foo>,
			iref: &'foo mut i32,
		}
	}
}
```

**Comment by jpernst** [comment]
Unfortunately not. The main purpose of rental is to abstract away the fact that the struct is self-referential, Using pin would make the struct immovable, which would effect the usability of the struct itself. Furthermore, the way pin works just isn't compatible with rental's API for a variety of other reasons.

However, there's another crate called [selfstack](https://crates.io/crates/selfstack) that has a similar goal to rental but works in a different way. You may find its approach more suitable.

**Comment by shepmaster** [comment]
>  the way pin works just isn't compatible with rental's API for a variety of other reasons.

As just a curious observer, I’d be interested to read those reasons, if you ever had some free time to spare! ❤️

**Comment by jpernst** [comment]
[This post](https://users.rust-lang.org/t/rental-0-5-released/17247/3) on the forum details some of the reasons.
