### ISSUE TITLE
Is it possible to gain mutable access to the head node?

### ISSUE THREAD

**Issue by TheDan64** [jpernst/rental#46]
I think you can do something like this with `into_head`, however, consuming my rental isn't ideal since it's a field(and `mem::swap`ing my struct would add allocations).

I know that you shouldn't be able to access the head mutably while you've borrowed the suffix, but maybe a rental method can take a mutable reference to the rental struct and pass it one closure for modifying the head mutably (which first drops the suffix), and a second closure(or more) for creating a new suffix afterwards like you do in `try_`/`new`?

**Comment by jpernst** [comment]
Such a thing is theoretically possible, but I'm not planning any further API additions for rental since I haven't written any rust in a few years and rental's code is pretty thorny.
