### ISSUE TITLE
Getting safely a reference from the suffix

### ISSUE THREAD

**Issue by TeXitoi** [jpernst/rental#6]
For
```rust
rental!{
    pub mod rent {
        use std;
        #[rental_mut]
        pub struct OwnedByteIter {
            v: Vec<u8>,
            iter: std::slice::Iter<'v, u8>,
        }
    }
}
```
Isn't it possible to generate something like that:
```rust
impl rent::OwnedByteIter {
    pub fn suffix_ref<'a>(&'a self) -> &'a std::slice::Iter<'a, u8> {
        self.iter.as_ref().unwrap()
    }
    pub fn suffix_mut<'a>(&'a mut self) -> &'a mut std::slice::Iter<'a, u8> {
        self.iter.as_mut().unwrap()
    }
}
```
It seems safe.

That'll make the lib much more ergonomic, flexible and powerful. For example, I can't find how do have a rental as rented part without using the unsafe borrow method.

**Comment by jpernst** [comment]
This definitely isn't safe in the general case, but is safe if the suffix type is variant over its rental lifetimes. I'll consider supporting this if I can think of a good way to mechanically enforce lifetime variance; probably via generating some kind of assert function that won't compile if the type is invariant.

To the more general point of storing a rental inside of a rental, you can do that with the `#[subrental]` attribute described in the macro docs. There's also some examples of it in the tests folder.

**Comment by TeXitoi** [comment]
OK, subrental is working here, thanks.

**Comment by jpernst** [comment]
Cool. I'll close this for now, but if other people need this feature for situations that aren't successfully covered by subrental then I'll revisit it.

**Comment by TeXitoi** [comment]
Well, the API that I can expose to my users would be much better with this functionality. Nothing wrong to have an open issue in your repository 😉

**Comment by jpernst** [comment]
The key problem is that it's not possible to expose this safely if there's any mutability involved. It would only be available on immutable borrows of immutable rental structs, and even then only if the value is variant. That use case seems narrow enough that the utility is pretty limited, but if that's still useful for people then I'll consider adding it.

**Comment by TeXitoi** [comment]
I have difficulties to understand the unsafe cases. Can you give examples of unsafe cases ?

I personally use it to compose iterators relying on borrowed data, and to have a movable quick_protobuf generated struct.

**Comment by jpernst** [comment]
The circumstances are subtle and difficult to summarize, but the nomicon section on [subtyping and variance](https://doc.rust-lang.org/nightly/nomicon/subtyping.html) describes the issues at play and gives some examples of how it can result in unsafety. In short, a mutable borrow will induce lifetime invariance in its target, which prevents us from exposing this API, since we can't safely coerce the lifetimes.
